# Generated by Django 4.2.7 on 2025-11-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shade_app', '0002_demonstration_remove_user_password_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temp123', max_length=255),
            preserve_default=False,
        ),
    ]
